Sample commands for AsciiDoc and DocBook
========================================
Shawn Giese
v1.0, October 2012

AsciiDoc files in these examples use the file extension .asciidoc to enable preview in github but you can use any extension that you prefer.  The components for this file structure must be downloaded separately if they are not installed in your operating system.

== Tools ==
.Free tools, required
The following free tools can create HTML and PDF output:

* AsciiDoc 
* DocBook XSL stylesheets
* Apache FOP
* Python 2.5 or later (for AsciiDoc)
* Java (for Apache FOP)
* Text editor like nano, TextWrangler or VIM
* The xsltproc tool

.Free tools, optional
AsciiDoc supports some free tools for additional content creation:

* Graphviz 
* QR code plugin
* pychart 

.Commercial tools, optional
The following are some optional commercial tools:

* XEP instead of Apache FOP - for more PDF options and advanced DocBook editing
* XMLMind XML editor instead of FOP - for output options like web help, Word, OpenOffice
* Sublime Text 2 instead of a free text editor - for advanced text editing

== Sample AsciiDoc commands ==
Convert AsciiDoc to Slidy presentation
----
asciidoc --backend slidy book1/book_simple.asciidoc 
----

Convert AsciiDoc to HTML5
----
asciidoc --backend html5 book1/book_simple.asciidoc 
----

Install qrcode plugin
----
asciidoc --backend install qrcode-filter.zip 
----

Convert AsciiDoc to DocBook file
----
asciidoc --backend docbook book1/book_simple.asciidoc 
----

Convert AsciiDoc to DocBook file and include docinfo.xml file
----
asciidoc -a docinfo1 --backend docbook book1/book_simple.asciidoc
----

Running AsciiDoc on Micriosoft Windows
----
python c:\mydocs\asciidoc-8.6.8\asciidoc.py -a docinfo1 -b docbook book1\book_simple.asciidoc
----

== Sample XSL conversions ==
Uses xsltproc and current XSL stylesheets to convert Docbook to FO. You must have already converted your document to a DocBook file with AsciiDoc.

Convert DocBook file to FO file
----
xsltproc.exe docbook-xsl-1.77.1/fo/docbook.xsl .\book1\book_simple.xml > \book1\output\book.fo
----

Rebuild custom title page layout from titlepage spec file
----
xsltproc.exe -o myTitlePage.xsl docbook-xsl-1.77.1\template\titlepage.xsl myTitlepageSpecFilexml
----

Convert DocBook file to FO file using a custom stylesheet
----
xsltproc.exe .\myCustomDocbook\myPDFstyles.xsl .\book1\book_simple.xml > \book1\output\book.fo
----

Convert DocBook file to FO file using a custom stylesheet an use xincludes (such as including legal text from a text file into the final output)
----
xsltproc.exe --xinclude .\myCustomDocbook\myPDFstyles.xsl .\book1\book_simple.xml > \book1\output\book.fo
----

.Additional information
The titlepage spec file should compile with any current XSL stylesheets for DocBook, however, I did not succeed with the 1.77.1 version and had to download the latest files from from http://50.56.245.89/xsl/template/ to correctly compile my custom titlepage.

Use of the titlepage spec file is discussed here https://lists.oasis-open.org/archives/docbook-apps/201207/msg00001.html

== Sample FOP commands ==
Uses Apache FOP to create PDF from FO file.

Convert FO file to PDF file
----
fop.bat .\book.fo .\book.pdf 
----

Convert FO file to PDF file and use custom FOP configuration		
----
fop.bat -c .\myFOPconf.xml .\book.fo .\book.pdf 
----

== Sample batch files for Windows ==
Although these examples are for Windows, similar scripts can be written for different operating systems. Batch files (or scripts) can be useful to integrate into your text editor to build previews of your documentation or to use with a continuous integration server to automate your workflow.  

For example, you can add custom build commands in the Sublime Text editor 

.Sample windows batch file
The custom FOP configuration file is for correctly associating fonts used in the PDF output.  This is not necessary when running FOP on MacOSX.  When running the same scripts in MacOSX, remove "-c .\myCustomPDF\myFOPconf.xml".

--------------------------------------
REM Batch file to create PDF from XML DocBook files
REM
REM build docbook XML file from AsciiDoc book
asciidoc -a docinfo1 -b docbook .\book1\book_simple.asciidoc

REM create a FO file 
xsltproc.exe --xinclude docbook-xsl-1.77.1/fo/docbook.xsl .\book1\book_simple.xml > .\book1\output\book.fo

REM create a PDF file 
fop-1.1\fop.bat -c .\myCustomPDF\myFOPconf.xml .\book1\output\book.fo .\book1\output\book.pdf 
--------------------------------------

.Sample windows batch file with customizations
--------------------------------------
REM Batch file to create PDF from XML DocBook files
REM
REM build docbook XML file from AsciiDoc book
asciidoc -a docinfo1 -b docbook book1\book_simple.asciidoc

REM create a FO file using a custom stylesheet
xsltproc.exe .\myCustomPDF\myPDFstyles.xsl .\book1\book_simple.xml > .\book1\output\book.fo

REM create a PDF file with some custom parameters to minimize errors
fop-1.1\fop.bat -c .\myCustomPDF\myFOPconf.xml .\book.fo .\book.pdf 
--------------------------------------

== Document file structure ==
Here is a sample document file structure for use with Windows. Tools such as asciidoc or xsltproc install to different folders in MacOSX or Linux.

	/mydocs
		xsltproc.exe
		/asciidoc-8.6.8
		/book1
			bookname.asciidoc
			docinfo.xml
			chap1.asciidoc
			chap2.asciidoc
			chap3.asciidoc
			glossary.asciidoc
			/images
			/output
		/book2
		/book3
		/common
			legal.txt
			/images
			/appendix
			MigrationNotes.asciidoc
		/docbook-xsl-1.77.1
		/fop-1.1
		/myCustomHTML
		/myCustomPDF
			myFOPconf.xml
			myPDFstyles.xsl
			myTitlePage.xsl
			myTitlepageSpecFile.xml

This is just one example. You can also store chapters or sections into subject or product folders and then keep the book files separate.
