[[advanced_features]]
Advanced usage
==============

== Advanced ==
AsciiDoc supports many advanced features such as:

* Creating a graphviz image
* Adding callouts
* Macros to include system commands
* Loading a CSV file into a table
* Conditional inclusion macros
* Embedding images in data-uri for XHTML output


=== Embed images in data-uri ===
This is built-in to AsciiDoc and enables you to convert your PNG images into base64 encodings that are included in the HTML output file. When you use this feature, the image data is included in the asciidoc file and avoids having to distribute the images files.

This is especially useful when exporting HTML because the images become embedded in the HTML itself. For more information read the AsciiDoc documentation for instructions using :data-uri:.

=== Graphviz charts ===
This requires that you install Graphviz on the computer that generates output. If you see the error message "IndexError: list index out of range" then Graphviz cannot be found. In case of such an error check that Graphviz is on your environment "PATH" variable. Depending on how Graphviz was installed, you also may need to run "dot -c" (with installer\'s privileges) to register the plugins.

[graphviz]
---------------------------------------------------------------------
digraph A {
  rankdir=LR; Graphviz->AsciiDoc->HTML}
---------------------------------------------------------------------

["graphviz", "../images/test_sample2.png"]
---------------------------------------------------------------------
digraph B {
  size ="8.5, 11";
  node [shape = circle];
  0 [ style = filled, color=lightgrey ];
  2 [ shape = doublecircle ];
  0 -> 2 [ label = "a " ];
  0 -> 1 [ label = "other " ];
  1 -> 2 [ label = "a " ];
  1 -> 1 [ label = "other " ];
  2 -> 2 [ label = "a " ];
  2 -> 1 [ label = "other " ];
  "Machine: a" [ shape = plaintext ];
}
---------------------------------------------------------------------

["graphviz", "../images/test_sample3.png"]
----
digraph C {
  "Start node" -> "End node" [label=" relationship"]
}
----


=== Callouts ===
Callouts functionality is built into AsciiDoc. Read the AsciiDoc documentation for instructions.

.MS-DOS directory listing
 -----------------------------------------------------
 10/17/97   9:04         <DIR>    bin
 10/16/97  14:11         <DIR>    DOS            <1>
 10/16/97  14:40         <DIR>    Program Files
 10/16/97  14:46         <DIR>    TEMP
 10/17/97   9:04         <DIR>    tmp
 10/16/97  14:37         <DIR>    WINNT
 10/16/97  14:25             119  AUTOEXEC.BAT   <2>
  2/13/94   6:21          54,619  COMMAND.COM
 10/16/97  14:25             115  CONFIG.SYS
 11/16/97  17:17      61,865,984  pagefile.sys
  2/13/94   6:21           9,349  WINA20.386     <3>
 -----------------------------------------------------

 <1> This directory holds MS-DOS.
 <2> System startup code for DOS.
 <3> Some sort of Windows 3.1 hack.

=== Macros ===
Run script on your system and incorporate that into the documentation. Using dir in a Windows environment. Change to a different command to match your OS.

------------------
sys::[dir -l *.asciidoc]
------------------

=== External scripts ===
For example, run an external script such as a pychart and then load the resulting image.

// Generate chart image file.
sys2::[python "{indir}/chartbar.py" > ../images/test.svg]

// Display chart image file.
image::../images/test.svg[scaledwidth="50%",alt="SVG output"]


=== Importing CSV data ===
[format="csv",cols="^1,4*2",options="header"]
|===================================================
ID,Customer Name,Contact Name,Customer Address,Phone
include::customers.csv[]
|===================================================
